version: '2.4'

services:
  release:
    image: icalialabs/alpha:release
    build:
      context: .
      target: release
    ports:
      - 3000:3000

  alpha:
    image: icalialabs/alpha:development
    build:
      context: .
      target: development
      args:
        - DEVELOPER_UID=${UID:-1000}
        - DEVELOPER_USER=${USER:-you}
    command: yarn start
    volumes:
      - .:/code
    ports:
      - 3000:3000

  install:
    extends:
      service: alpha
    command: yarn install
